//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_activos
    {
        public int id_agencia { get; set; }
        public string id_serie { get; set; }
        public string id_ficha { get; set; }
        public string id_sio { get; set; }
        public int id_fabricante { get; set; }
        public byte id_tipo { get; set; }
        public byte id_modelo { get; set; }
        public byte id_marca { get; set; }
        public byte id_logotipo { get; set; }
        public byte[] foto { get; set; }
        public int estado { get; set; }
        public string no_contrato { get; set; }
        public Nullable<int> fabricado { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public int tiene_imagen { get; set; }
        public int id_negocio { get; set; }
        public int trasladado { get; set; }
        public Nullable<System.DateTime> fecha_traslado { get; set; }
        public int id_orden_traslado { get; set; }
        public Nullable<System.DateTime> fecha_orden_traslado { get; set; }
        public int viejo { get; set; }
        public int visitado { get; set; }
        public int id_orden_trabajo { get; set; }
        public string hora { get; set; }
        public int dia { get; set; }
        public Nullable<System.DateTime> fecha_visita { get; set; }
        public Nullable<int> vuelta { get; set; }
        public int id_problema { get; set; }
        public string id_activo { get; set; }
        public string instalacion { get; set; }
        public Nullable<System.DateTime> fecha_instalacion { get; set; }
        public string etiqueta { get; set; }
    }
}
